# Ejercicios de Pandas con Iris

Soluciones de los nueve ejercicios. Los resultados se obtienen de los CSV que acompañan este cuaderno.

**Objetivo:** repetir con un dataset diferente las operaciones vistas con Pingüinos: explorar, seleccionar, filtrar, agrupar, limpiar, transformar y exportar.

**Importante:** usa el material de referencia, documentación y, si lo deseas, un asistente de IA. Debes **entender y comprobar** el código. Las celdas están intencionadamente sin resolver.

## Preparación
Este archivo usa una copia didáctica del dataset Iris con **8 celdas vacías introducidas para practicar limpieza**. Son 150 flores, tres especies y cuatro mediciones. Los datos originales se guardan en `iris_original.csv` para comparar.

Coloca este notebook en la misma carpeta que los archivos CSV. Si aparece `FileNotFoundError`, revisa la carpeta abierta en VS Code.

In [1]:
import pandas as pd

iris = pd.read_csv("iris_con_faltantes.csv")
print("Dataset cargado:", iris.shape)
display(iris.head(3))

Dataset cargado: (150, 5)

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa

**Comprobación esperada:** `(150, 5)`.

**Referencia de columnas:** `sepal_length_cm`, `sepal_width_cm`, `petal_length_cm`, `petal_width_cm`, `species`. Las medidas están expresadas en centímetros.

## Ejercicio 1. Explorar el dataset

a) Muestra las primeras cinco filas. b) Identifica las dimensiones. c) Consulta los tipos de columna y sus valores no nulos. d) Encuentra cuáles especies aparecen en la columna `species`.

**Pista:** Recuerda `head`, `shape`, `info` y `unique`. Debes encontrar **3 especies**.

In [2]:
display(iris.head())
print("Dimensiones:", iris.shape)
iris.info()
print("Especies:", iris["species"].unique())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             NaN              1.4             0.2  setosa

Dimensiones: (150, 5)
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepal_length_cm  150 non-null    float64
 1   sepal_width_cm   145 non-null    float64
 2   petal_length_cm  150 non-null    float64
 3   petal_width_cm   147 non-null    float64
 4   species          150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB
Especies: <StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

**Respuesta:** Hay **150 filas y 5 columnas**. Las cuatro mediciones son numéricas (float64) y species contiene texto. Las especies son setosa, versicolor y virginica. Hay 145 valores registrados en sepal_width_cm, 147 en petal_width_cm y 150 en las demás columnas.

## Ejercicio 2. Seleccionar columnas y posiciones

a) Crea una tabla que contenga solo `species` y `petal_length_cm`. b) Muestra **las cinco primeras filas y las dos primeras columnas** mediante posiciones, no nombres.

**Pista:** Usa una lista de columnas para (a) y `iloc` para (b). El final de un slice no se incluye.

In [3]:
seleccion = iris[["species", "petal_length_cm"]]
display(seleccion)

primeras_posiciones = iris.iloc[:5, :2]
display(primeras_posiciones)

       species  petal_length_cm
0       setosa              1.4
1       setosa              1.4
2       setosa              1.3
3       setosa              1.5
4       setosa              1.4
..         ...              ...
145  virginica              5.2
146  virginica              5.0
147  virginica              5.2
148  virginica              5.4
149  virginica              5.1

[150 rows x 2 columns]

   sepal_length_cm  sepal_width_cm
0              5.1             3.5
1              4.9             3.0
2              4.7             3.2
3              4.6             3.1
4              5.0             NaN

**Respuesta:** La primera tabla contiene solo la especie y la longitud del pétalo. iloc[:5, :2] selecciona las filas de posición 0 a 4 y las columnas de posición 0 y 1: longitud y ancho del sépalo.

## Ejercicio 3. Filtrar con una o dos condiciones

a) Selecciona solamente flores de la especie `setosa`. b) Selecciona flores de `virginica` cuyo `petal_length_cm` sea **mayor que 5.5**. c) Muestra cuántas filas tiene cada resultado.

**Pista:** Utiliza una máscara de comparación y `&`; cada condición debe ir entre paréntesis.

In [4]:
setosa = iris[iris["species"] == "setosa"]
virginica_larga = iris[
    (iris["species"] == "virginica") & (iris["petal_length_cm"] > 5.5)
]

display(setosa)
display(virginica_larga)
print("Flores setosa:", len(setosa))
print("Virginica con pétalos mayores que 5.5 cm:", len(virginica_larga))

    sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0               5.1             3.5              1.4             0.2  setosa
1               4.9             3.0              1.4             0.2  setosa
2               4.7             3.2              1.3             0.2  setosa
3               4.6             3.1              1.5             0.2  setosa
4               5.0             NaN              1.4             0.2  setosa
5               5.4             3.9              1.7             0.4  setosa
6               4.6             3.4              1.4             0.3  setosa
7               5.0             3.4              1.5             0.2  setosa
8               4.4             2.9              1.4             0.2  setosa
9               4.9             3.1              1.5             0.1  setosa
10              5.4             3.7              1.5             0.2  setosa
11              4.8             3.4              1.6             0.2  setosa
12              4.8             3.0              1.4             NaN  setosa
13              4.3             3.0              1.1             0.1  setosa
14              5.8             4.0              1.2             0.2  setosa
15              5.7             4.4              1.5             0.4  setosa
16              5.4             3.9              1.3             0.4  setosa
17              5.1             3.5              1.4             0.3  setosa
18              5.7             3.8              1.7             0.3  setosa
19              5.1             3.8              1.5             0.3  setosa
20              5.4             3.4              1.7             0.2  setosa
21              5.1             3.7              1.5             0.4  setosa
22              4.6             3.6              1.0             0.2  setosa
23              5.1             3.3              1.7             0.5  setosa
24              4.8             3.4              1.9             0.2  setosa
25              5.0             3.0              1.6             0.2  setosa
26              5.0             3.4              1.6             0.4  setosa
27              5.2             3.5              1.5             0.2  setosa
28              5.2             3.4              1.4             0.2  setosa
29              4.7             3.2              1.6             0.2  setosa
30              4.8             3.1              1.6             0.2  setosa
31              5.4             3.4              1.5             0.4  setosa
32              5.2             4.1              1.5             0.1  setosa
33              5.5             4.2              1.4             0.2  setosa
34              4.9             3.1              1.5             0.2  setosa
35              5.0             3.2              1.2             0.2  setosa
36              5.5             3.5              1.3             0.2  setosa
37              4.9             NaN              1.4             0.1  setosa
38              4.4             3.0              1.3             0.2  setosa
39              5.1             3.4              1.5             0.2  setosa
40              5.0             3.5              1.3             0.3  setosa
41              4.5             2.3              1.3             0.3  setosa
42              4.4             3.2              1.3             0.2  setosa
43              5.0             3.5              1.6             0.6  setosa
44              5.1             3.8              1.9             0.4  setosa
45              4.8             3.0              1.4             0.3  setosa
46              5.1             3.8              1.6             0.2  setosa
47              4.6             3.2              1.4             0.2  setosa
48              5.3             3.7              1.5             0.2  setosa
49              5.0             3.3              1.4             0.2  setosa

     sepal_length_cm  sepal_width_cm  ...  petal_width_cm    species
100              6.3             3.3  ...             NaN  virginica
102              7.1             3.0  ...             2.1  virginica
103              6.3             2.9  ...             1.8  virginica
104              6.5             3.0  ...             2.2  virginica
105              7.6             3.0  ...             2.1  virginica
107              7.3             2.9  ...             1.8  virginica
108              6.7             2.5  ...             1.8  virginica
109              7.2             3.6  ...             2.5  virginica
117              7.7             3.8  ...             2.2  virginica
118              7.7             2.6  ...             2.3  virginica
120              6.9             NaN  ...             2.3  virginica
122              7.7             2.8  ...             2.0  virginica
124              6.7             3.3  ...             2.1  virginica
125              7.2             3.2  ...             1.8  virginica
128              6.4             2.8  ...             2.1  virginica
129              7.2             3.0  ...             1.6  virginica
130              7.4             2.8  ...             1.9  virginica
131              7.9             3.8  ...             2.0  virginica
132              6.4             2.8  ...             2.2  virginica
134              6.1             2.6  ...             1.4  virginica
135              7.7             3.0  ...             2.3  virginica
136              6.3             3.4  ...             2.4  virginica
140              6.7             3.1  ...             2.4  virginica
143              6.8             3.2  ...             2.3  virginica
144              6.7             3.3  ...             2.5  virginica

[25 rows x 5 columns]

Flores setosa: 50
Virginica con pétalos mayores que 5.5 cm: 25

**Respuesta:** Hay **50 flores setosa** y **25 virginica** con pétalos de más de 5.5 cm. La comparación es estricta: los pétalos que miden exactamente 5.5 cm no entran en el segundo resultado.

## Ejercicio 4. Contar y agrupar por especie

a) Cuenta cuántas flores hay de cada especie. b) Calcula el **promedio de `petal_length_cm` para cada especie**. c) Identifica cuál tiene el promedio mayor.

**Pista:** Busca `value_counts`, `groupby` y `mean`. La columna `petal_length_cm` no contiene faltantes en esta copia.

In [5]:
conteo = iris["species"].value_counts()
promedios = iris.groupby("species")["petal_length_cm"].mean()

print("Flores por especie:")
print(conteo)
print("\nPromedio de longitud del pétalo en cm:")
print(promedios)
print("\nEspecie con el promedio mayor:", promedios.idxmax())

Flores por especie:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Promedio de longitud del pétalo en cm:
species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length_cm, dtype: float64

Especie con el promedio mayor: virginica

**Respuesta:** Cada especie tiene **50 flores**. El promedio de longitud del pétalo es **1.462 cm** para setosa, **4.260 cm** para versicolor y **5.552 cm** para virginica. El promedio mayor corresponde a **virginica**.

## Ejercicio 5. Limpiar valores faltantes y quitar columnas

a) Cuenta cuántos valores faltan por columna. b) Crea **una copia** sin las filas que tengan valores vacíos y cuenta cuántas quedan. c) Crea otra copia donde rellenes únicamente los faltantes de `sepal_width_cm` con su mediana. d) Crea una tercera copia sin la columna `petal_width_cm`. **No modifiques `iris` directamente.**

**Pista:** Recuerda `isna().sum()`, `dropna()`, `fillna()`, `median()` y `drop(columns=[...])`. Esperamos **142 filas completas** antes de rellenar.

In [6]:
print("Faltantes por columna:")
print(iris.isna().sum())

iris_sin_faltantes = iris.dropna().copy()
print("\nFilas completas:", len(iris_sin_faltantes))

iris_rellenado = iris.copy()
mediana_ancho_sepalo = iris["sepal_width_cm"].median()
iris_rellenado["sepal_width_cm"] = iris_rellenado["sepal_width_cm"].fillna(
    mediana_ancho_sepalo
)
print("\nMediana del ancho del sépalo:", mediana_ancho_sepalo)
print("Faltantes después del relleno:")
print(iris_rellenado.isna().sum())

iris_sin_ancho_petalo = iris.drop(columns=["petal_width_cm"]).copy()
print("\nColumnas de la tercera copia:", iris_sin_ancho_petalo.columns.tolist())
print("Faltantes en iris, sin modificar:", iris.isna().sum().sum())

Faltantes por columna:
sepal_length_cm    0
sepal_width_cm     5
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64

Filas completas: 142

Mediana del ancho del sépalo: 3.0
Faltantes después del relleno:
sepal_length_cm    0
sepal_width_cm     0
petal_length_cm    0
petal_width_cm     3
species            0
dtype: int64

Columnas de la tercera copia: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'species']
Faltantes en iris, sin modificar: 8

**Respuesta:** Faltan **5 valores de ancho del sépalo** y **3 de ancho del pétalo**. Al eliminar las filas incompletas quedan **142**. La mediana del ancho del sépalo es **3.0 cm**; al rellenar solo esa columna quedan 3 faltantes, todos en el ancho del pétalo. La copia sin petal_width_cm tiene 4 columnas. Son tres alternativas separadas e iris conserva sus 150 filas, 5 columnas y 8 faltantes.

## Ejercicio 6. Transformar columnas

a) Crea en una copia una nueva columna `petal_length_mm` convirtiendo centímetros a milímetros. b) Crea otra columna `species_codigo` asignando `S`, `V` y `G` a las tres especies. c) Comprueba cinco filas.

**Pista:** Para la conversión basta una operación sobre toda la columna; para códigos puedes usar `.map()` con un diccionario. Si quieres, prueba también `.apply(lambda ...)`.

In [7]:
iris_transformado = iris.copy()
iris_transformado["petal_length_mm"] = iris_transformado["petal_length_cm"] * 10

codigos = {"setosa": "S", "versicolor": "V", "virginica": "G"}
iris_transformado["species_codigo"] = iris_transformado["species"].map(codigos)

display(iris_transformado.head())

   sepal_length_cm  sepal_width_cm  ...  petal_length_mm  species_codigo
0              5.1             3.5  ...             14.0               S
1              4.9             3.0  ...             14.0               S
2              4.7             3.2  ...             13.0               S
3              4.6             3.1  ...             15.0               S
4              5.0             NaN  ...             14.0               S

[5 rows x 7 columns]

**Respuesta:** Se multiplica por **10** para pasar de centímetros a milímetros: por ejemplo, 1.4 cm son 14 mm. Se asigna S a setosa, V a versicolor y G a virginica. La copia transformada tiene **150 filas y 7 columnas**; la tabla iris sigue sin cambios.

## Ejercicio 7. Exportar el resultado

a) Guarda el DataFrame transformado del ejercicio 6 en `iris_procesado.csv`, **sin guardar la columna de índice**. b) Vuelve a leer el CSV con Pandas y comprueba que conserva 150 filas y las nuevas columnas.

**Pista:** Usa `to_csv` con `index=False` y después `read_csv`.

In [8]:
iris_transformado.to_csv("iris_procesado.csv", index=False)
iris_leido = pd.read_csv("iris_procesado.csv")

print("Dimensiones del CSV:", iris_leido.shape)
print("Columnas:", iris_leido.columns.tolist())
print("Conserva 150 filas:", len(iris_leido) == 150)
print("Conserva las columnas nuevas:",
      {"petal_length_mm", "species_codigo"}.issubset(iris_leido.columns))
print("Sin columna de índice adicional:",
      iris_leido.columns.tolist() == iris_transformado.columns.tolist())
display(iris_leido.head())

Dimensiones del CSV: (150, 7)
Columnas: ['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'species', 'petal_length_mm', 'species_codigo']
Conserva 150 filas: True
Conserva las columnas nuevas: True
Sin columna de índice adicional: True

   sepal_length_cm  sepal_width_cm  ...  petal_length_mm  species_codigo
0              5.1             3.5  ...             14.0               S
1              4.9             3.0  ...             14.0               S
2              4.7             3.2  ...             13.0               S
3              4.6             3.1  ...             15.0               S
4              5.0             NaN  ...             14.0               S

[5 rows x 7 columns]

**Respuesta:** El archivo exportado tiene **150 filas y 7 columnas**, incluidas petal_length_mm y species_codigo, y no agrega una columna de índice. Conserva los 8 faltantes porque el ejercicio 6 transforma una copia de iris, no la copia rellenada del ejercicio 5.

## Ejercicio 8. Unir filas con `concat`

a) Construye dos DataFrames: primeras 50 filas y siguientes 50 filas de `iris`. b) Únelos verticalmente y comprueba el número total de filas.

**Pista:** Combina `iloc` y `pd.concat`; prueba `ignore_index=True`.

In [9]:
primeras_50 = iris.iloc[:50].copy()
siguientes_50 = iris.iloc[50:100].copy()
iris_unido = pd.concat([primeras_50, siguientes_50], ignore_index=True)

print("Filas del primer grupo:", len(primeras_50))
print("Filas del segundo grupo:", len(siguientes_50))
print("Dimensiones de la unión:", iris_unido.shape)
print("Índice:", iris_unido.index.min(), "a", iris_unido.index.max())
display(iris_unido.head())

Filas del primer grupo: 50
Filas del segundo grupo: 50
Dimensiones de la unión: (100, 5)
Índice: 0 a 99

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             NaN              1.4             0.2  setosa

**Respuesta:** Las dos partes tienen 50 filas cada una. concat produce una tabla de **100 filas y 5 columnas**, con un índice nuevo de 0 a 99. Contiene las primeras 100 observaciones de iris, sin añadir las últimas 50.

## Ejercicio 9. Relacionar tablas con `merge`
Crea una tabla pequeña con las columnas `species` y `codigo`: setosa→S, versicolor→V y virginica→G. Une esta tabla con `iris` mediante la especie. Verifica que aparecen 150 filas y una columna adicional. Los códigos son solamente etiquetas didácticas.

**Pista:** Puedes construir la tabla auxiliar con `pd.DataFrame({...})` y hacer un `merge` por `species`.

In [10]:
tabla_codigos = pd.DataFrame({
    "species": ["setosa", "versicolor", "virginica"],
    "codigo": ["S", "V", "G"]
})
display(tabla_codigos)

iris_con_codigos = iris.merge(tabla_codigos, on="species", how="left")
print("Dimensiones tras merge:", iris_con_codigos.shape)
print("Códigos sin asignar:", iris_con_codigos["codigo"].isna().sum())
display(iris_con_codigos.head())
display(iris_con_codigos[["species", "codigo"]].drop_duplicates())

      species codigo
0      setosa      S
1  versicolor      V
2   virginica      G

Dimensiones tras merge: (150, 6)
Códigos sin asignar: 0

   sepal_length_cm  sepal_width_cm  ...  species  codigo
0              5.1             3.5  ...   setosa       S
1              4.9             3.0  ...   setosa       S
2              4.7             3.2  ...   setosa       S
3              4.6             3.1  ...   setosa       S
4              5.0             NaN  ...   setosa       S

[5 rows x 6 columns]

        species codigo
0        setosa      S
50   versicolor      V
100   virginica      G

**Respuesta:** La unión tiene **150 filas y 6 columnas**. Se añade codigo y no quedan códigos vacíos. No se duplican flores porque cada especie aparece una sola vez en la tabla auxiliar.

## Antes de entregar
**Guarde en un Github creado Público** `git status` → `git add .` → `git commit -m "Practicar consultas y transformaciones con Pandas"`. Evita subir al repositorio archivos de entornos virtuales (`.venv/`).

## Comprobación final

Se compara la tabla de trabajo con los CSV de entrada y se revisan las dimensiones, las copias y la exportación.

In [11]:
iris_entrada = pd.read_csv("iris_con_faltantes.csv")
iris_original = pd.read_csv("iris_original.csv")

pd.testing.assert_frame_equal(iris, iris_entrada)
assert iris.shape == (150, 5)
assert iris.isna().sum().to_dict() == {
    "sepal_length_cm": 0, "sepal_width_cm": 5,
    "petal_length_cm": 0, "petal_width_cm": 3, "species": 0
}
assert iris_original.isna().sum().sum() == 0
# Los valores observados coinciden con el CSV original.
assert iris.eq(iris_original).where(iris.notna(), True).all().all()
assert seleccion.columns.tolist() == ["species", "petal_length_cm"]
pd.testing.assert_frame_equal(primeras_posiciones, iris.iloc[:5, :2])
assert len(setosa) == 50 and len(virginica_larga) == 25
assert conteo.to_dict() == {"setosa": 50, "versicolor": 50, "virginica": 50}
assert promedios.round(3).to_dict() == {
    "setosa": 1.462, "versicolor": 4.260, "virginica": 5.552
}
assert promedios.idxmax() == "virginica"
assert iris_sin_faltantes.shape == (142, 5)
assert mediana_ancho_sepalo == 3.0
assert iris_rellenado.isna().sum().sum() == 3
assert iris_rellenado["sepal_width_cm"].isna().sum() == 0
pd.testing.assert_frame_equal(
    iris_rellenado.drop(columns=["sepal_width_cm"]),
    iris.drop(columns=["sepal_width_cm"])
)
assert iris_sin_ancho_petalo.shape == (150, 4)
assert "petal_width_cm" not in iris_sin_ancho_petalo.columns
assert iris_transformado.shape == (150, 7)
assert (iris_transformado["petal_length_mm"] == iris["petal_length_cm"] * 10).all()
assert iris_transformado["species_codigo"].equals(iris["species"].map(codigos))
pd.testing.assert_frame_equal(iris_leido, iris_transformado)
pd.testing.assert_frame_equal(iris_unido, iris.iloc[:100].reset_index(drop=True))
assert iris_con_codigos.shape == (150, 6)
assert iris_con_codigos["codigo"].notna().all()
pd.testing.assert_frame_equal(iris_con_codigos.drop(columns=["codigo"]), iris)
print("Todas las comprobaciones pasaron. La tabla iris y los CSV de entrada se conservaron.")

Todas las comprobaciones pasaron. La tabla iris y los CSV de entrada se conservaron.